version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - assignmenta
      - assignmentb:
          requires:
            - assignmenta
      - compile
      - test:
          requires:
            - compile
      - analyze:
          requires:
            - test

# default: &default

commands:
  getDependenciesnBuild:
    description: "Get Basic Dependencies and build"
    steps:
      - checkout
      - run: npm install

jobs:

  compile:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - getDependenciesnBuild

  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - getDependenciesnBuild
      - run: npm run lint
  analyze:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - getDependenciesnBuild
      - run: npm audit


  assignmenta:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run: mkdir -p workspace
      - run: echo "say yaay" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  assignmentb:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      - run: return 1
      - run:
          name: Testy
          command: echo "Were ti fail sha"
          when: on_fail
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
